CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    userName VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(15) NOT NULL,
    dateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);